
  // List of major cities that should have limited radius
  export const majorCities = [
    'new york', 'los angeles', 'chicago', 'houston', 'phoenix', 'philadelphia',
    'san antonio', 'san diego', 'dallas', 'san jose', 'austin', 'jacksonville',
    'fort worth', 'columbus', 'charlotte', 'san francisco', 'indianapolis',
    'seattle', 'denver', 'washington', 'boston', 'el paso', 'detroit',
    'nashville', 'portland', 'memphis', 'oklahoma city', 'las vegas',
    'baltimore', 'milwaukee', 'albuquerque', 'tucson', 'fresno', 'sacramento',
    'kansas city', 'mesa', 'atlanta', 'omaha', 'colorado springs', 'raleigh',
    'miami', 'oakland', 'minneapolis', 'tulsa', 'cleveland', 'wichita',
    'arlington', 'bakersfield', 'tampa', 'aurora', 'honolulu', 'anaheim',
    'santa ana', 'corpus christi', 'riverside', 'lexington', 'stockton',
    'toledo', 'st. paul', 'newark', 'greensboro', 'plano', 'henderson',
    'lincoln', 'buffalo', 'jersey city', 'chula vista', 'fort wayne',
    'orlando', 'st. petersburg', 'chandler', 'laredo', 'norfolk', 'madison',
    'lubbock', 'irvine', 'winston-salem', 'glendale', 'garland', 'hialeah',
    'reno', 'chesapeake', 'gilbert', 'baton rouge', 'irving', 'scottsdale',
    'north las vegas', 'fremont', 'boise', 'richmond', 'san bernardino',
    'birmingham', 'spokane', 'rochester', 'des moines', 'modesto', 'fayetteville',
    'tacoma', 'oxnard', 'fontana', 'columbus', 'montgomery', 'moreno valley',
    'shreveport', 'aurora', 'yonkers', 'akron', 'huntington beach', 'little rock',
    'augusta', 'amarillo', 'glendale', 'mobile', 'grand rapids', 'salt lake city',
    'tallahassee', 'huntsville', 'grand prairie', 'knoxville', 'worcester',
    'newport news', 'brownsville', 'overland park', 'santa clarita',
    'providence', 'garden grove', 'chattanooga', 'oceanside', 'jackson',
    'fort lauderdale', 'santa rosa', 'rancho cucamonga', 'port st. lucie',
    'tempe', 'ontario', 'vancouver', 'cape coral', 'sioux falls', 'springfield',
    'peoria', 'pembroke pines', 'elk grove', 'salem', 'lancaster', 'corona',
    'eugene', 'palmdale', 'salinas', 'springfield', 'pasadena', 'fort collins',
    'hayward', 'pomona', 'cary', 'rockford', 'alexandria', 'escondido',
    'mckinney', 'kansas city', 'joliet', 'sunnyvale', 'torrance', 'bridgeport',
    'lakewood', 'hollywood', 'paterson', 'naperville', 'syracuse', 'mesquite',
    'dayton', 'savannah', 'clarksville', 'orange', 'pasadena', 'fullerton',
    'killeen', 'frisco', 'hampton', 'mcallen', 'warren', 'west valley city',
    'columbia', 'olathe', 'sterling heights', 'new haven', 'miramar',
    'waco', 'thousand oaks', 'cedar rapids', 'charleston', 'sioux city',
    'round rock', 'fargo', 'evansville', 'daly city', 'richardson',
    'pueblo', 'temecula', 'manchester', 'lewisville', 'cambridge',
    'carrollton', 'pearland', 'fairfield', 'billings', 'lowell',
    'san buenaventura', 'clinton', 'murfreesboro', 'norwalk', 'rialto',
    'inglewood', 'burbank', 'arvada', 'ann arbor', 'tuscaloosa',
    'berkeley', 'rochester', 'independence', 'beaumont', 'provo',
    'palm bay', 'el monte', 'columbia', 'lansing', 'westminster',
    'st. louis', 'high point', 'clearwater', 'costa mesa', 'miami gardens',
    'downey', 'manchester', 'elgin', 'west jordan', 'broken arrow',
    'inglewood', 'antioch', 'gresham', 'sandy springs', 'tyler',
    'league city', 'hillsboro', 'allentown', 'concord', 'ventura',
    'centennial', 'dearborn', 'victorville', 'westland', 'allen',
    'abilene', 'round rock', 'surprise', 'erie', 'lakewood',
    'cambridge', 'norman', 'boulder', 'portsmouth', 'west palm beach',
    'tuscaloosa', 'edinburg', 'lowell', 'woodbridge', 'sugar land',
    'brockton', 'lynn', 'missouri city', 'pearland', 'clovis',
    'green bay', 'visalia', 'west covina', 'carlsbad', 'athens',
    'topeka', 'vallejo', 'el cajon', 'davenport', 'roseville',
    'santa clara', 'compton', 'beaumont', 'amherst', 'odessa',
    'quincy', 'livonia', 'nashua', 'somerville', 'new bedford',
    'richmond', 'toms river', 'cranston', 'jurupa valley', 'brick township',
    'coral springs', 'davie', 'midland', 'st. petersburg', 'dearborn heights',
    'lafayette', 'plantation', 'miami beach', 'college station', 'lee\'s summit',
    'edinburg', 'carmel', 'macon', 'beaverton', 'portsmouth', 'troy',
    'new rochelle', 'bloomington', 'farmington hills', 'reading',
    'sparks', 'yakima', 'billings', 'hammond', 'gary', 'south bend',
    'missoula', 'clifton', 'san marcos', 'mission', 'springfield',
    'bryan', 'rochester', 'cicero', 'flint', 'south gate',
    'lawrence', 'lake forest', 'warwick', 'rio rancho', 'asheville',
    'sandy', 'meridian', 'yuma', 'st. joseph', 'tempe', 'merced',
    'dayton', 'hammond', 'concord', 'thousand oaks', 'fremont',
    'cambridge', 'bend', 'lynn', 'clifton', 'longmont',
    'lorain', 'new britain', 'west haven', 'daly city', 'somerville',
    'cambridge', 'norwalk', 'mission viejo', 'edison', 'stamford',
    'lynn', 'elizabeth', 'camden', 'glendale', 'redwood city',
    'westminster', 'allen', 'albany', 'brockton', 'fall river',
    'kennewick', 'norwalk', 'manchester', 'reading',
    // International major cities
    'london', 'paris', 'berlin', 'madrid', 'rome', 'amsterdam', 'barcelona',
    'vienna', 'brussels', 'munich', 'hamburg', 'cologne', 'milan', 'naples',
    'turin', 'palermo', 'genoa', 'bologna', 'florence', 'venice',
    'moscow', 'st. petersburg', 'tokyo', 'osaka', 'kyoto', 'yokohama',
    'nagoya', 'kobe', 'fukuoka', 'sapporo', 'kawasaki', 'saitama',
    'beijing', 'shanghai', 'guangzhou', 'shenzhen', 'chengdu', 'hangzhou',
    'wuhan', 'xi\'an', 'nanjing', 'chongqing', 'tianjin', 'suzhou',
    'mumbai', 'delhi', 'bangalore', 'hyderabad', 'chennai', 'kolkata',
    'pune', 'jaipur', 'lucknow', 'kanpur', 'nagpur', 'visakhapatnam',
    'sydney', 'melbourne', 'brisbane', 'perth', 'adelaide', 'gold coast',
    'newcastle', 'canberra', 'sunshine coast', 'wollongong',
    'toronto', 'montreal', 'vancouver', 'calgary', 'edmonton', 'ottawa',
    'winnipeg', 'quebec city', 'hamilton', 'kitchener', 'london',
    'victoria', 'halifax', 'oshawa', 'windsor', 'saskatoon',
    'são paulo', 'rio de janeiro', 'brasília', 'salvador', 'fortaleza',
    'belo horizonte', 'manaus', 'curitiba', 'recife', 'goiânia',
    'belém', 'porto alegre', 'guarulhos', 'campinas', 'são luís',
    'mexico city', 'guadalajara', 'monterrey', 'puebla', 'toluca',
    'tijuana', 'león', 'juárez', 'torreón', 'querétaro', 'san luis potosí',
    'mérida', 'mexicali', 'aguascalientes', 'cuernavaca', 'saltillo',
    'buenos aires', 'córdoba', 'rosario', 'mendoza', 'tucumán',
    'la plata', 'mar del plata', 'salta', 'santa fe', 'san juan',
    'resistencia', 'santiago', 'valparaíso', 'concepción', 'la serena',
    'antofagasta', 'temuco', 'rancagua', 'talca', 'arica',
    'lima', 'arequipa', 'callao', 'trujillo', 'chiclayo', 'huancayo',
    'piura', 'iquitos', 'cusco', 'chimbote', 'tacna', 'ica',
    'bogotá', 'medellín', 'cali', 'barranquilla', 'cartagena',
    'cúcuta', 'bucaramanga', 'pereira', 'santa marta', 'ibagué',
    'pasto', 'manizales', 'neiva', 'soledad', 'villavicencio',
    'caracas', 'maracaibo', 'valencia', 'barquisimeto', 'maracay',
    'ciudad guayana', 'san cristóbal', 'maturín', 'ciudad bolívar',
    'cumana', 'barcelona', 'puerto la cruz', 'cabimas', 'turmero',
    'cairo', 'alexandria', 'giza', 'shubra el kheima', 'port said',
    'suez', 'luxor', 'aswan', 'asyut', 'ismailia', 'fayyum',
    'zagazig', 'damietta', 'assiut', 'minya', 'damanhur',
    'cape town', 'johannesburg', 'durban', 'pretoria', 'port elizabeth',
    'pietermaritzburg', 'benoni', 'tembisa', 'east london', 'vereeniging',
    'bloemfontein', 'boksburg', 'welkom', 'newcastle', 'krugersdorp',
    'lagos', 'kano', 'ibadan', 'kaduna', 'port harcourt', 'benin city',
    'maiduguri', 'zaria', 'aba', 'jos', 'ilorin', 'oyo',
    'enugu', 'abeokuta', 'abuja', 'sokoto', 'onitsha', 'warri',
    'accra', 'kumasi', 'tamale', 'cape coast', 'sekondi-takoradi',
    'tema', 'koforidua', 'wa', 'sunyani', 'ho',
    'addis ababa', 'dire dawa', 'mek\'ele', 'gondar', 'awasa',
    'bahir dar', 'dessie', 'jimma', 'jijiga', 'shashamane',
    'nairobi', 'mombasa', 'nakuru', 'eldoret', 'kisumu', 'thika',
    'malindi', 'kitale', 'garissa', 'kakamega', 'machakos',
    'kampala', 'gulu', 'lira', 'mbarara', 'jinja', 'mbale',
    'mukono', 'kasese', 'masaka', 'hoima', 'arua', 'kabale',
    'dar es salaam', 'mwanza', 'arusha', 'dodoma', 'mbeya',
    'morogoro', 'tanga', 'kahama', 'tabora', 'kigoma', 'moshi',
    'lusaka', 'ndola', 'kitwe', 'kabwe', 'chingola', 'mufulira',
    'luanshya', 'kasama', 'chipata', 'livingstone', 'mazabuka',
    'harare', 'bulawayo', 'chitungwiza', 'mutare', 'gweru',
    'kwekwe', 'kadoma', 'masvingo', 'chinhoyi', 'norton',
    'maputo', 'matola', 'beira', 'nampula', 'chimoio', 'nacala',
    'quelimane', 'tete', 'xai-xai', 'maxixe', 'pemba',
    'gaborone', 'francistown', 'molepolole', 'serowe', 'selibe phikwe',
    'maun', 'lobatse', 'kanye', 'mochudi', 'mahalapye',
    'maseru', 'teyateyaneng', 'mafeteng', 'hlotse', 'mohale\'s hoek',
    'qacha\'s nek', 'quthing', 'butha-buthe', 'mokhotlong', 'thaba-tseka',
    'mbabane', 'manzini', 'lobamba', 'siteki', 'nhlangano',
    'piggs peak', 'big bend', 'malkerns', 'simunye', 'lavumisa'
  ];
