name: Next.js CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies (with caching for speed)
      - name: Install dependencies
        run: npm ci

      # 4. Run ESLint
      - name: Run ESLint
        run: npm run lint --if-present

      # 5. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 6. Run tests
      - name: Run tests
        run: npm run test --if-present

  deploy:
    needs: build-and-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Vercel CLI
      - run: npm install -g vercel

      # Deploy to Vercel
      - run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
